<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>catalogo">Producto</a></li>
    <li class="active">Catalogo de Productos</li>
  </ol>
  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Catalogo de Productos</h1>
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Catalogo de Productos</div>
        </div>
        <div class="panel-body">
          <table class="table table-hover" id="tablaCatalogo" width="100%">
            <thead>
              <tr>
                <th>#</th>
                <th>COD. KARDEX</th>
                <th>COD. PRODUCTO</th>
                <th>PRODUCTO</th>
                <th>MARCA</th>
                <th>MODELO</th>
                <th>PRECIO (unidad)</th>
                <th>CANT. COMPRADA</th>
                <th>CANT. VENDIDA</th>
                <th>STOCK ACTUAL</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


</div>
