<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>stock?idLocal=<?php echo $this->idLocal; ?>"><?php echo $this->nombreLocal; ?></a></li>
    <li class="active">Stock de Productos</li>
  </ol>
  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Stock de Productos</h1>
  </div>

  <div class="row">

    <div class="form-group col-sm-12 hide">
      <label class="control-label required" for="required-input">Cod. Local</label>
      <input type="text" class="form-control numeros" id="codLocal" name="codLocal" value="<?php echo $this->idLocal; ?>">
    </div>

    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Stock de Productos</div>
        </div>       

        <div class="panel-body table-responsive">
          <table class="table table-hover" id="tablaStock" width="100%">
            <thead>
              <tr>
                <th>COD. PRODUCTO</th>
                <th>PRODUCTO</th>
                <th>STOCK</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


</div>
