<!-- jQuery UI -->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>anulacion?idLocal=<?php echo $this->idLocal; ?>"><?php echo $this->nombreLocal; ?></a></li>
    <li class="active">Anulacion</li>
  </ol>
  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Anulacion de Compra - Local: <?php echo $this->nombreLocal; ?></h1>
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Busqueda</div>
        </div>
        <div class="panel-body">

          <form class="smart-form" id="formAnulacion">

              <div class="form-group col-sm-4 hide">
                <label class="control-label required" for="required-input">Cod. Local</label>
                <input type="text" class="form-control numeros" id="codLocal" name="codLocal" value="<?php echo $this->idLocal; ?>">
              </div>

              <div class="form-group col-sm-4">
                <label class="control-label" for="required-input">Cod. Compra</label>
                <input type="text" class="form-control numeros" id="codCompra" name="codCompra">
              </div>

              <div class="form-group col-sm-4">
                <label class="control-label required" for="required-input">Fecha Inicio Compra</label>
                <input type="date" class="form-control" id="fechaInicio" name="fechaInicio">
              </div>

              <div class="form-group col-sm-4">
                <label class="control-label required" for="required-input">Fecha Fin Compra</label>
                <input type="date" class="form-control" id="fechaFin" name="fechaFin">
              </div>

              <div class="form-group col-sm-12">
                <div class="form-group has-error">              
                  <small class="form-message" id="msj_anulacion"></small>
                </div>
              </div>

          </form>          
          
        </div>

        <div class="panel-footer text-right">
          <button type="button" id="btnBuscar" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Buscar</button>
        </div>

      </div>
      
        <div class="row">    
          <div class="col-md-12">
            <div class="panel">
              <div class="panel-heading">
                <div class="panel-title">Compras Filtradas</div>
              </div>
              <div class="panel-body">
                <table class="table table-hover" id="tablaCompra" width="100%">
                  <thead>
                    <tr>
                      <th>FECHA COMPRA</th>
                      <th>COD. COMPRA</th>
                      <th>PROVEEDOR</th>
                      <th>CANTIDAD COMPRA</th>
                      <th>COSTO COMPRA</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>

</div>

<div class="modal fade" id="mDetalleCompra" tabindex="-1">

  <div class="modal-dialog modal-lg">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Anular Compra</h4>
      </div>

      <div class="modal-body">

        <form class="" id="form_compra_detalle">
          <div class="row">
            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Cod. Compra</label>
              <input type="text" class="form-control" id="idcompra" name="idcompra" autocomplete="off" maxlength="15" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Fecha Compra</label>
              <input type="text" class="form-control" id="fechaCompra" name="fechaCompra" autocomplete="off" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Proveedor</label>
              <input type="text" class="form-control" id="sProveedor" name="sProveedor" autocomplete="off" maxlength="100" readonly="readonly">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Observacion</label>
              <textarea class="form-control" id="observacion" name="observacion" autocomplete="off" readonly="readonly"></textarea>
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Motivo</label>
              <textarea class="form-control" id="motivo" name="motivo" autocomplete="off"></textarea>
            </div>

          </div>

          <ul class="nav nav-tabs nav-xs" id="tab-resize-xs">
            <li class="active"><a href="#tabDetalleCompra" data-toggle="tab">Detalle Compra</a></li>
            <li><a href="#tabDetalleVenta" data-toggle="tab">Venta Realizadas</a></li>
          </ul>

          <div class="tab-content">

            <div class="tab-pane active" id="tabDetalleCompra">

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Producto</th>
                        <th class="p-x-2">Cantidad</th>
                        <th class="p-x-2">Precio Unidad</th>
                        <th class="p-x-2">Total</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetalleCompra">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td>Cant. Total</td>
                        <td> <strong><span id="cantidadTotalCompra"></span></strong> </td>
                        <td>Precio Total</td>
                        <td> <strong><span id="precioTotalCompra"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>                
              </div>

            </div>
            
            <div class="tab-pane" id="tabDetalleVenta">
              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Fecha Venta</th>
                        <th class="p-x-2">Cod. Venta</th>
                        <th class="p-x-2">Cantidad</th>
                        <th class="p-x-2">Importe</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetalleVenta">
                    </tbody>
                  </table>
                </div>                
              </div>
            </div>

          </div>          
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-danger" id="btnAnular">Anular</button>
      </div>
    </div>

  </div>

</div>