<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>venta">Venta</a></li>
    <li class="active">Registro de Venta</li>
  </ol>
  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Registro de Venta</h1>
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Formulario de Venta</div>
        </div>
        <div class="panel-body">

          <form class="smart-form" id="formVenta">

            <section class="col-sm-6">

              <div class="form-group col-sm-12">
                <label class="control-label required" for="required-input">Seleccionar Producto</label>
                <select class="form-control" id="idProducto" name="idProducto" >
                  <option selected="selected" disabled="disabled">--SELECCIONE--</option>
                  <?php while($reg=$this->productos->fetch_object()): ?>
                  <option value="<?php echo $reg->IDPRODUCTO; ?>"><?php echo $reg->NOMBRE; ?></option>
                  <?php endwhile; ?>
                </select>
              </div>

              <div class="form-group col-sm-12">
                <label class="control-label required" for="required-input">Seleccionar Alias (Compra)</label>
                <select class="form-control" id="idCompra" name="idCompra">
                </select>            
              </div>

              <div class="form-group col-sm-6">
                <label class="control-label required" for="required-input">Cantidad</label>
                <input type="text" class="form-control numeros" id="cantidad" name="cantidad" autocomplete="off">
              </div>

              <div class="form-group col-sm-6">
                <label class="control-label required" for="required-input">Precio Venta (Unidad)</label>
                <input type="text" class="form-control numerospunto" id="precioVenta" name="precioVenta" autocomplete="off">
              </div>

              <div class="form-group col-sm-6">
                <label class="control-label required" for="required-input">Stock Actual</label>
                <input type="text" class="form-control" id="stockActual" name="stockActual" autocomplete="off" readonly="readonly">
              </div>

              <div class="form-group col-sm-6">
                <label class="control-label required" for="required-input">Precio Total</label>
                <input type="text" class="form-control" id="precioTotal" name="precioTotal" autocomplete="off" readonly="readonly">
              </div>              

              <div class="form-group col-sm-12">
                <label lass="control-label" for="required-input">Observacion</label>
                  <textarea rows="3" class="form-control" name="observacion" id="observacion"></textarea>
              </div>
              
              <div class="form-group col-sm-12">
                <div class="form-group has-error">              
                  <small class="form-message" id="msj_venta"></small>
                </div>
              </div>

            </section>
                    

          </form>
          
        </div>

        <div class="panel-footer text-right">
          <button type="button" id="btnRegistrar" class="btn btn-primary"><span class="btn-label-icon right fa fa-save"></span> Registrar</button>
        </div>

      </div>
    </div>
  </div>

</div>