<!-- jQuery UI -->
<!-- <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css"> -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script> -->
<style> 
a.buttons-collection {
        margin-left: 1em;
    }
</style>
<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>reporte?idLocal=<?php echo $this->idLocal; ?>"><?php echo $this->nombreLocal; ?></a></li>
    <li class="active">Reportes Generales</li>
  </ol>

  <div class="form-group col-sm-4 hide">
    <label class="control-label required" for="required-input">Cod. Local</label>
    <input type="text" class="form-control numeros" id="codLocal" name="codLocal" value="<?php echo $this->idLocal; ?>">
  </div>

  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Reportes Generales</h1>
  </div>

  <div class="row">
    <div class="panel-body">
      <ul class="nav nav-tabs">
        <li class="active">
          <a href="#tabs-1" data-toggle="tab" aria-expanded="true">
            Ventas
          </a>
        </li>
        <li class="">
          <a href="#tabs-2" data-toggle="tab" aria-expanded="false">
            Compras
          </a>
        </li>
        <li class="">
          <a href="#tabs-5" data-toggle="tab" aria-expanded="false">
            Cuentas por Pagar
          </a>
        </li>
        <li class="">
          <a href="#tabs-6" data-toggle="tab" aria-expanded="false">
            Cuentas por Cobrar
          </a>
        </li>
        <li class="">
          <a href="#tabs-7" data-toggle="tab" aria-expanded="false">
            Inversion Actual
          </a>
        </li>
        <li class="">
          <a href="#tabs-8" data-toggle="tab" aria-expanded="false">
            Resumen Venta
          </a>
        </li>
      </ul>

      <div class="tab-content tab-content-bordered">
        <div class="tab-pane fade active in" id="tabs-1">
          <p>
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-heading">
                  <div class="panel-title">Filtros</div>

                </div>
                <div class="panel-body">

                  <form class="smart-form" id="formReporte1">
                    <div class="form-group col-md-12">
                      <select class="form-control" id="tipoVenta" name="tipoVenta">
                        <option value="1">ACTIVAS</option>
                        <option value="4">EXTORNADAS</option>
                      </select>
                    </div>
                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Inicio</label>
                      <input type="date" class="form-control" id="fechaInicio1" name="fechaInicio1">
                    </div>

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Fin</label>
                      <input type="date" class="form-control" id="fechaFin1" name="fechaFin1">
                    </div>

                  </form>
                </div>

                <div class="panel-footer text-right">
                  <button type="button" id="btnBuscar" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Buscar</button>
                </div>

              </div>
              <div class="row">
                <div class="row">
                  <div class="col-md-12">

                    <div class="row">
                      <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading">
                            <div class="panel-title">Detalle de Busqueda</div>
                          </div>
                          <div class="panel-body">
                            <table class="table table-striped" id="tblReporteventas" width="100%">
                              <thead>
                                <tr>
                                  <th> Fecha Venta</th>
                                  <th> Cod. Venta</th>
                                  <th> Cliente</th>
                                  <th> Costo</th>
                                  <th> Pago</th>
                                  <th> Deuda</th>
                                  <th> Proforma</th>
                                </tr>
                              </thead>
                              <tbody id="">
                              </tbody>
                              <tfoot>
                                <tr>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                </tr>

                              </tfoot>

                            </table>
                          </div>
                        </div>
                      </div>
                    </div>


                  </div>
                </div>
              </div>

            </div>
        </div>
        </p>

        <div class="tab-pane" id="tabs-2">
          <p>

            <div class="col-md-12">
              <div class="panel">
                <div class="panel-heading">
                  <div class="panel-title">Filtros</div>
                </div>
                <div class="panel-body">

                  <form class="smart-form" id="formReporte2">

                    <div class="form-group col-md-12">
                      <select class="form-control" id="tipoCompra" name="tipoCompra">
                        <option value="1">ACTIVAS</option>
                        <option value="3">ANULADAS</option>

                      </select>
                    </div>

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Inicio</label>
                      <input type="date" class="form-control" id="fechaInicio2" name="fechaInicio2">
                    </div>

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Fin</label>
                      <input type="date" class="form-control" id="fechaFin2" name="fechaFin2">
                    </div>

                    <div class="form-group col-sm-12">
                      <div class="form-group has-error">
                        <small class="form-message" id="msj_reporte"></small>
                      </div>
                    </div>

                  </form>

                </div>

                <div class="panel-footer text-right">
                  <button type="button" id="btnBuscarCompras" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Buscar</button>
                </div>

              </div>
              <div class="row">
                <div class="row">
                  <div class="col-md-12">

                    <div class="row">
                      <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading">
                            <div class="panel-title">Detalle de Busqueda</div>
                          </div>
                          <div class="panel-body table-responsive">
                            <table class="table table-hover" id="tblReportecompras" width="100%">
                              <thead>
                                <tr>

                                  <th> Fecha </th>
                                  <th> Local </th>
                                  <th> idCompra </th>
                                  <th> Proveedor </th>
                                  <th> Cantidad Total </th>
                                  <th> Costo Total </th>
                                  <th> Pago Total Compra </th>
                                  <th> Deuda </th>
                                  <th> Opciones </th>
                                </tr>
                              </thead>
                              <tbody id="">
                              </tbody>
                              <tfoot>
                              <tr>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                </tr>
                              </tfoot>

                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
        </p>

        <div class="tab-pane fade" id="tabs-5">
          <p>
            <!-- InicioTab -->
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-heading">
                  <div class="panel-title">Filtros</div>
                </div>
                <div class="panel-body">
                  <form class="smart-form" id="formReporte3">
                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Inicio</label>
                      <input type="date" class="form-control" id="fechaInicio5" name="fechaInicio5">
                    </div>

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Fin</label>
                      <input type="date" class="form-control" id="fechaFin5" name="fechaFin5">
                    </div>

                    <div class="form-group col-sm-12">
                      <div class="form-group has-error">
                        <small class="form-message" id="msj_reporte"></small>
                      </div>
                    </div>

                  </form>

                </div>

                <div class="panel-footer text-right">
                  <button type="button" id="btnBuscar5" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span>Buscar</button>
                </div>

              </div>
              <div class="row">
                <div class="row">
                  <div class="col-md-12">

                    <div class="row">
                      <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading">
                            <div class="panel-title">Detalle de Busqueda</div>
                          </div>
                          <div class="panel-body table-responsive">
                            <table class="table table-hover" id="tblReporteCuentasxPagar" width="100%">
                              <thead>
                                <tr>
                                  <th>Fecha Compra</th>
                                  <th>Cod. Compra</th>
                                  <th>Proveedor</th>
                                  <th>Cant. Productos</th>>
                                  <th>Costo Total</th>
                                  <th>Pago Total</th>
                                  <th>Deuda Total</th>
                                </tr>
                              </thead>
                              <tbody id="">
                              </tbody>
                              <tfoot>
                              <tr>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                </tr>
                              </tfoot>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Fin Tab -->
          </p>
        </div>
        <div class="tab-pane fade" id="tabs-6">
          <p>
            <!-- InicioTab -->
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-heading">
                  <div class="panel-title">Filtros</div>
                </div>
                <div class="panel-body">

                  <form class="smart-form" id="formReporte4">

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Inicio</label>
                      <input type="date" class="form-control" id="fechaInicio6" name="fechaInicio6">
                    </div>

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Fin</label>
                      <input type="date" class="form-control" id="fechaFin6" name="fechaFin6">
                    </div>

                    <div class="form-group col-sm-12">
                      <div class="form-group has-error">
                        <small class="form-message" id="msj_reporte"></small>
                      </div>
                    </div>

                  </form>

                </div>

                <div class="panel-footer text-right">
                  <button type="button" id="btnBuscar6" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Buscar</button>
                </div>

              </div>
              <div class="row">
                <div class="row">
                  <div class="col-md-12">

                    <div class="row">
                      <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading">
                            <div class="panel-title">Detalle de Busqueda</div>
                          </div>
                          <div class="panel-body table-responsive">
                            <table class="table table-hover" id="tblReporteCuentasxCobrar" width="100%">
                              <thead>
                                <tr>
                                  <th> Fecha Venta </th>
                                  <th> Cod. Venta </th>
                                  <th> Cliente </th>
                                  <th> Cant. Productos </th>
                                  <th> Costo Total </th>
                                  <th> Pago Total </th>
                                  <th> Deuda Total </th>
                                </tr>
                              </thead>
                              <tbody id="">
                              <tr>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                </tr>
                              </tbody>
                              <tfoot>
                              </tfoot>

                            </table>
                          </div>
                        </div>
                      </div>
                    </div>


                  </div>
                </div>
              </div>

            </div>
            <!-- Fin Tab -->
          </p>
        </div>

        <div class="tab-pane fade" id="tabs-7">
          <p>
            <div class="col-md-12">
              <div class="row">
                <div class="row">
                  <div class="col-md-12">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading">
                            <div class="panel-title">Detalle de Busqueda</div>
                          </div>
                          <div class="panel-body table-responsive">
                            <table class="table table-hover" id="tblReporteInversion" width="100%">
                              <thead>
                                <tr>
                                  <th> Cod. Producto </th>
                                  <th> Producto </th>
                                  <th> Stock </th>
                                  <th> Inversión </th>
                                  <th> Precio Promedio </th>
                                  <th> Avg Total </th>
                                </tr>
                              </thead>
                              <tbody id="">
                              </tbody>
                              <tfoot>
                              <tr>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  
                                </tr>
                              </tfoot>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </p>
        </div>

        <div class="tab-pane fade" id="tabs-8">
          <p>
            <!-- InicioTab -->
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-heading">
                  <div class="panel-title">Filtros</div>
                </div>
                <div class="panel-body">

                  <form class="smart-form" id="formReporte5">

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Inicio</label>
                      <input type="date" class="form-control" id="fechaInicio8" name="fechaInicio8">
                    </div>

                    <div class="form-group col-sm-6">
                      <label class="control-label required" for="required-input">Fecha Fin</label>
                      <input type="date" class="form-control" id="fechaFin8" name="fechaFin8">
                    </div>

                    <div class="form-group col-sm-12">
                      <div class="form-group has-error">
                        <small class="form-message" id="msj_reporte"></small>
                      </div>
                    </div>

                  </form>

                </div>

                <div class="panel-footer text-right">
                  <button type="button" id="btnBuscar8" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Buscar</button>
                </div>

              </div>
              <div class="row">
                <div class="row">
                  <div class="col-md-12">

                    <div class="row">
                      <div class="col-md-12">
                        <div class="panel">
                          <div class="panel-heading">
                            <div class="panel-title">Detalle de Busqueda</div>
                          </div>
                          <div class="panel-body table-responsive">
                            <table class="table table-hover" id="tblReporteBalance" width="100%">
                              <thead>
                                <tr>
                                  <th> Fecha </th>
                                  <th> Cant. Ventas </th>
                                  <th> Cant. Productos Vendidos </th>
                                  <th> Venta Total </th>
                                  <th> Pago Efectivo </th>
                                  <th> Pago Deposito </th>
                                  <th> Credito / por Cobrar </th>
                                </tr>
                              </thead>
                              <tbody id="">
                              </tbody>
                              <tr>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                  <th></th>
                                </tr>
                              <tfoot>
                              </tfoot>

                            </table>
                          </div>
                        </div>
                      </div>
                    </div>


                  </div>
                </div>
              </div>

            </div>
            <!-- Fin Tab -->
          </p>
        </div>
      </div>

    </div>

  </div>
</div>

<div class="modal fade" id="mDetallefactura" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Proforma</h4>
      </div>
      <div class="modal-body">
        <div id="pdf_viewer">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="mDetalleVenta" tabindex="-1">

  <div class="modal-dialog modal-lg">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Detalle Venta</h4>
      </div>

      <div class="modal-body">

        <form class="" id="form_venta_detalle">
          <div class="row">
            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Cod. Venta</label>
              <input type="text" class="form-control" id="idVenta" name="idVenta" autocomplete="off" maxlength="15" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Fecha Venta</label>
              <input type="text" class="form-control" id="fechaVenta" name="fechaVenta" autocomplete="off" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Cliente</label>
              <input type="text" class="form-control" id="sCliente" name="sCliente" autocomplete="off" maxlength="100" readonly="readonly">
            </div>


          </div>

          <ul class="nav nav-tabs nav-xs" id="tab-resize-xs">
            <li class="active"><a href="#tabDetalleVenta" data-toggle="tab">Detalle Compra</a></li>
            <li><a href="#tabDetallePago" data-toggle="tab">Detalle Pago</a></li>
          </ul>

          <div class="tab-content">

            <div class="tab-pane active" id="tabDetalleVenta">

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Producto</th>
                        <th class="p-x-2">Cantidad</th>
                        <th class="p-x-2">Precio Unidad</th>
                        <th class="p-x-2">Total</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetalleVenta">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td>Cant. Total</td>
                        <td> <strong><span id="cantidadTotalVenta"></span></strong> </td>
                        <td>Precio Total</td>
                        <td> <strong><span id="precioTotalVenta"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>

            </div>

            <div class="tab-pane" id="tabDetallePago">

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Fecha Pago</th>
                        <th class="p-x-2">Tipo Pago</th>
                        <th class="p-x-2">Nro Cuenta</th>
                        <th class="p-x-2">Monto</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetallePago">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td style="text-align: center;">Deuda Total</td>
                        <td> <strong><span id="deudaTotalVenta"></span></strong> </td>
                        <td style="text-align: center;">Pago Total</td>
                        <td> <strong><span id="montoTotalPago"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>

            </div>

          </div>



        </form>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

  </div>
</div>

<div class="modal fade" id="mDetalleCompra" tabindex="-1">

  <div class="modal-dialog modal-lg">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Cuentas por Pagar</h4>
      </div>

      <div class="modal-body">

        <form class="" id="form_compra_detalle">
          <div class="row">
            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Cod. Compra</label>
              <input type="text" class="form-control" id="idcompra" name="idcompra" autocomplete="off" maxlength="15" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Fecha Compra</label>
              <input type="text" class="form-control" id="fechaCompra" name="fechaCompra" autocomplete="off" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Proveedor</label>
              <input type="text" class="form-control" id="sProveedor" name="sProveedor" autocomplete="off" maxlength="100" readonly="readonly">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Observacion Compra</label>
              <textarea class="form-control" id="observacionCompra" name="observacionCompra" autocomplete="off" readonly="readonly"></textarea>
            </div>

          </div>

          <ul class="nav nav-tabs nav-xs" id="tab-resize-xs">

            <li class="active"><a href="#tabDetallecompra" data-toggle="tab">Detalle Compra</a></li>
            <li class=""><a href="#tabDetallePagocompra" data-toggle="tab">Detalle Pago</a></li>

          </ul>

          <div class="tab-content">



            <div class="tab-pane active" id="tabDetallecompra">

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Producto</th>
                        <th class="p-x-2">Cantidad</th>
                        <th class="p-x-2">Precio Unidad</th>
                        <th class="p-x-2">Total</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetalleCompra">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td>Cant. Total</td>
                        <td> <strong><span id="cantidadTotalCompra"></span></strong> </td>
                        <td>Precio Total</td>
                        <td> <strong><span id="precioTotalCompra"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>



            </div>

            <div class="tab-pane" id="tabDetallePagocompra">

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Fecha Pago</th>
                        <th class="p-x-2">Tipo Pago</th>
                        <th class="p-x-2">Nro Cuenta</th>
                        <th class="p-x-2">Monto</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetallePagoCompras">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td style="text-align: center;">Deuda Total</td>
                        <td> <strong><span id="deudaTotalCompra"></span></strong> </td>
                        <td style="text-align: center;">Pago Total</td>
                        <td> <strong><span id="montoTotalPagoCompra"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>

            </div>

          </div>



        </form>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

  </div>

</div>