<!-- jQuery UI -->
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>cuentacobro?idLocal=<?php echo $this->idLocal; ?>"><?php echo $this->nombreLocal; ?></a></li>
    <li class="active">Cuentas</li>
  </ol>
  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Cuentas Por Cobrar</h1>
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Busqueda</div>
        </div>
        <div class="panel-body">

          <form class="smart-form" id="formExtorno">

              <div class="form-group col-sm-4 hide">
                <label class="control-label required" for="required-input">Cod. Local</label>
                <input type="text" class="form-control numeros" id="codLocal" name="codLocal" value="<?php echo $this->idLocal; ?>">
              </div>

              <div class="form-group col-sm-4">
                <label class="control-label required" for="required-input">Cod. Venta</label>
                <input type="text" class="form-control numeros" id="codVenta" name="codVenta">
              </div>

              <div class="form-group col-sm-4">
                <label class="control-label required" for="required-input">Fecha Inicio Venta</label>
                <input type="date" class="form-control" id="fechaInicio" name="fechaInicio">
              </div>

              <div class="form-group col-sm-4">
                <label class="control-label required" for="required-input">Fecha Fin Venta</label>
                <input type="date" class="form-control" id="fechaFin" name="fechaFin">
              </div>

          </form>          
          
        </div>

        <div class="panel-footer text-right">
          <button type="button" id="btnBuscar" class="btn btn-primary"><span class="btn-label-icon right fa fa-search"></span> Buscar</button>
        </div>

      </div>
      
        <div class="row">    
          <div class="col-md-12">
            <div class="panel">
              <div class="panel-heading">
                <div class="panel-title">Ventas Filtradas</div>
              </div>
              <div class="panel-body">
                <table class="table table-hover" id="tblCuentasPorCobrar" width="100%">
                  <thead>
                    <tr>
                      <th>FECHA VENTA</th>
                      <th>COD. VENTA</th>
                      <th>CLIENTE</th>
                      <th>IMPORTE GENERADO</th>
                      <th>IMPORTE PAGADO</th>
                      <th>DEUDA</th>
                    </tr>
                  </thead>
                  <tbody>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

    </div>
  </div>

</div>

<div class="modal fade" id="mDetalleVenta" tabindex="-1">

  <div class="modal-dialog modal-lg">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">Cuentas por Cobrar</h4>
      </div>

      <div class="modal-body">

        <form class="" id="form_venta_detalle">
          <div class="row">
            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Cod. Venta</label>
              <input type="text" class="form-control" id="idVenta" name="idVenta" autocomplete="off" maxlength="15" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Fecha Venta</label>
              <input type="text" class="form-control" id="fechaVenta" name="fechaVenta" autocomplete="off" readonly="readonly">
            </div>

            <div class="form-group col-sm-4">
              <label class="control-label required" for="required-input">Cliente</label>
              <input type="text" class="form-control" id="sCliente" name="sCliente" autocomplete="off" maxlength="100" readonly="readonly">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Observacion Venta</label>
              <textarea class="form-control" id="observacionVenta" name="observacionVenta" autocomplete="off" readonly="readonly"></textarea>
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label" for="required-input">Observacion Pago</label>
              <textarea class="form-control" id="observacionVentaPago" name="observacionVentaPago" autocomplete="off"></textarea>
            </div>

            <div class="form-group col-sm-3">
              <label class="control-label required" for="required-input">Fecha Pago</label>
              <input type="date" class="form-control" id="fechaPago" name="fechaPago">
            </div>

            <div class="form-group col-sm-3">
              <label class="control-label required" for="required-input">Forma Pago</label>
                <select class="form-control" id="formaPago" name="formaPago"></select>
            </div>

            <div class="form-group col-sm-3" id="divCuenta">
              <label class="control-label required" for="required-input">N° Cuenta</label>
              <input type="text" class="form-control hide" id="idCuenta" name="idCuenta" autocomplete="off">
              <input type="text" class="form-control" id="cuenta" name="cuenta" autocomplete="off">
            </div>

            <div class="form-group col-sm-3">
              <label class="control-label required" for="required-input">Monto</label>
                <input type="text" class="form-control numerospunto" id="montopago" name="montopago" autocomplete="off">
            </div>

          </div>

          <ul class="nav nav-tabs nav-xs" id="tab-resize-xs">
            <li class="active"><a href="#tabDetalleCompra" data-toggle="tab">Detalle Compra</a></li>
            <li><a href="#tabDetallePago" data-toggle="tab">Detalle Pago</a></li>
          </ul>

          <div class="tab-content">

            <div class="tab-pane active" id="tabDetalleCompra">

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Producto</th>
                        <th class="p-x-2">Cantidad</th>
                        <th class="p-x-2">Precio Unidad</th>
                        <th class="p-x-2">Total</th>
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetalleVenta">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td>Cant. Total</td>
                        <td> <strong><span id="cantidadTotalVenta"></span></strong> </td>
                        <td>Precio Total</td>
                        <td> <strong><span id="precioTotalVenta"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>            
              </div>

            </div>
            
            <div class="tab-pane" id="tabDetallePago">    

              <div class="row">
                <div class="table-responsive">
                  <table class="table m-a-0">
                    <thead>
                      <tr class="bg-white darken">
                        <th class="p-x-2">Fecha Pago</th>
                        <th class="p-x-2">Tipo Pago</th>
                        <th class="p-x-2">Nro Cuenta</th>
                        <th class="p-x-2">Monto</th>                        
                      </tr>
                    </thead>
                    <tbody class="font-size-14" id="tBodyDetallePago">
                    </tbody>
                    <tfoot>
                      <tr class="info">
                        <td style="text-align: center;">Deuda Total</td>
                        <td> <strong><span id="deudaTotalVenta"></span></strong> </td>
                        <td style="text-align: center;">Pago Total</td>
                        <td> <strong><span id="montoTotalPago"></span></strong> </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>            
              </div>

            </div>

          </div>

          

        </form>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-danger" id="btnPagar">Pagar</button>
      </div>
    </div>

  </div>

</div>