<style type="text/css">
.ui-autocomplete { z-index:2147483647; }

</style>
<div class="px-content">
  <ol class="breadcrumb page-breadcrumb">
    <li><a href="<?php echo BASE_URL; ?>producto">Producto</a></li>
    <li class="active">Compra Producto</li>
  </ol>
  <div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i></span>Registrar Compra</h1>
  </div>


  <div class="panel-body">
    <button type="button" id="btnNuevaCompra" class="btn btn-md btn-primary btn-outline btn-3d btn-block" data-toggle="modal" data-target="#mAddCompra">Registrar Compra</button>      
  </div>

  <div class="row">    
    <div class="col-md-12">
      <div class="panel">
        <div class="panel-heading">
          <div class="panel-title">Historial de Compras</div>
        </div>
        <div class="panel-body">
          <table class="table table-hover" id="tablaCompra" width="100%">
            <thead>
              <tr>
                <th>#</th>
                <th>FECHA COMPRA</th>
                <th>COD. COMPRA</th>
                <th>COD. PRODUCTO</th>
                <th>PRODUCTO</th>
                <th>ALIAS</th>
                <th>CANTIDAD</th>                
                <th>PRECIO UNIDAD</th>
                <th>PRECIO TOTAL</th>
                <th>OPCIONES</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


</div>

<div class="modal fade" id="mAddCompra" role="dialog" aria-hidden="true" aria-labelledby="mAddCompraLabel">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title" id="title_compra">Registrar Compra</h4>
      </div>
      <div class="modal-body">

        <form class="smart-form" id="formCompra">

          <div class="row">

            <div class="form-group col-sm-6 hide">
              <label class="control-label" for="required-input">ID Compra</label>
              <input type="text" class="form-control" id="idCompra" name="idCompra" autocomplete="off" readonly="readonly">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Nombre del Producto</label>
              <input type="text" class="form-control" id="nombre" name="nombre" autocomplete="off">
            </div>            

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Cantidad</label>
              <input type="text" class="numeros form-control" id="cantidad" name="cantidad" autocomplete="off">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Precio Compra (x Unidad)</label>
              <input type="text" class="form-control numerospunto" id="precioCompra" name="precioCompra" autocomplete="off">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label required" for="required-input">Alias de Compra</label>
              <input type="text" class="form-control" id="aliasCompra" name="aliasCompra" autocomplete="off">
            </div>

            <div class="form-group col-sm-6">
              <label class="control-label" for="required-input">Descripcion</label>
              <textarea class="form-control" id="descripcion" name="descripcion" autocomplete="off" rows="4"></textarea>            
            </div>

          </div>

        </form>

        <div class="form-group has-error">              
          <small class="form-message" id="msj_compra"></small>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Cerrar</button>        
        <button type="button" class="btn btn-primary m-r-1" id="btn_add_compra">Guardar</button>
        <button type="button" class="btn btn-primary m-r-1" id="btn_update_compra">Actualizar</button>
      </div>
    </div>
  </div>
</div>

